language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

install:
  - composer install

before_script:
  - phpenv config-add install/travis-7.x.ini

script: 
  - mkdir -p build/logs
  - vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs --ignore=vendor --standard=coding_standard.xml .

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
